version = 1

test_patterns = [
  "**/*_test.rb",
  "  **/*_spec.rb",
  "  **/spec/**",
  "  **/test/**",
  "  **/features/**",
  "  **/fixtures/**",
  "  **/dummy/**",
  "  **/test/**/*",
  "  **/spec/**/*",
  "  .rspec",
  "  .simplecov",
  "  spec_helper.rb",
  "  rails_helper.rb"
]

# Ignore code coverage for test files
coverage = { exclude_patterns = ["**/*_spec.rb", "**/spec/**/*", "**/test/**/*"] }

[[analyzers]]
name = "javascript"
disabled = false

[analyzers.meta]
environment = [
  "browser",
  "jquery"
]

# Use project's ESLint configuration
[analyzers.meta.eslint]
  config = ".eslintrc.json"
  ignore = [
    "**/vendor/**",
    "**/node_modules/**",
    "**/public/**",
    "**/tmp/**"
  ]

# Disable specific rules that are handled by our ESLint config
[analyzers.meta.rules]
  "no-var" = "off"  # Handled by ESLint
  "strict" = "off"  # Handled by ESLint
  "no-shadow" = "off"  # Handled by ESLint

[[analyzers]]
name = "ruby"

disabled = false

[analyzers.meta]
  [analyzers.meta.rails]
  enabled = true
  version = "6.1"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"
