version = 1

test_patterns = [
  "**/*_test.rb",
  "  **/*_spec.rb",
  "  **/spec/**",
  "  **/test/**",
  "  **/features/**",
  "  **/fixtures/**",
  "  **/dummy/**",
  "  **/test/**/*",
  "  **/spec/**/*",
  "  .rspec",
  "  .simplecov",
  "  spec_helper.rb",
  "  rails_helper.rb"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "ruby"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"