# Be sure to restart your server when you modify this file.

# Configure parameters to be filtered from the log file. Use this to limit dissemination of
# sensitive information. See the ActiveSupport::ParameterFilter documentation for supported
# notations and behaviors.
Rails.application.config.filter_parameters += [
  :password,
  :password_confirmation,
  :card_number,
  :card_code,
  :cvv,
  :cvv2,
  :cvc,
  :account_number,
  :routing_number,
  :bank_account_number,
  :iban,
  :card_expiry,
  :expiration_date,
  :expiry_date,
  :exp_month,
  :exp_year,
  :verification_value,
  :verification_code,
  :token,
  :auth_code,
  :transaction_id,
  :phone,
  :phone_number,
  :mobile_number,
  :ssn,
  :social_security_number,
  :tax_id,
  :date_of_birth,
  :dob,
  :secret,
  :api_key,
  :access_token,
  :refresh_token,
  :authorization,
  :auth_token,
  :session_token,
  :session_id,
  :authenticity_token,
  :_method,
  :authenticity_token,
  :commit,
  :utf8,
  :authenticity_token,
  :_method,
  :commit,
  :utf8,
  :authenticity_token,
  :_method,
  :commit,
  :utf8,
  :authenticity_token,
  :_method,
  :commit,
  :utf8
]
