---
# Elastic APM Configuration
# Only enabled when ELASTIC_APM_ENABLED=true
enabled: <%= ENV['ELASTIC_APM_ENABLED'] == 'true' %>

# Server configuration
server_url: <%= ENV['ELASTIC_APM_SERVER_URL'] || 'http://localhost:8200' %>
secret_token: <%= ENV['ELASTIC_APM_SECRET_TOKEN'] || '' %>

# Security settings
capture_body: never
capture_headers: false
log_level: <%= ENV['ELASTIC_APM_LOG_LEVEL'] || 'error' %>

# Performance tuning
metrics_interval: 30s
span_frames_min_duration: 5ms
transaction_sample_rate: <%= ENV['ELASTIC_APM_SAMPLE_RATE'] || '0.1' %>
transaction_max_spans: 100

# Data collection settings
capture_elasticsearch_queries: false
capture_redis: false
capture_memcached: false
record_sql: none
stack_trace_limit: 0

# Error collection
error:
  collect: true
  ignore_exceptions: 'ActionController::RoutingError,ActiveRecord::RecordNotFound,ActiveRecord::RecordInvalid'

# Metrics collection
metrics:
  collect: true
  interval: 30s

# Environment-specific overrides
development:
  log_level: info
  transaction_sample_rate: 1.0
  capture_headers: false

test:
  enabled: false

production:
  log_level: error
  transaction_sample_rate: 0.1
  capture_headers: false
  ignore_patterns:
    - "^/healthcheck"
    - "^/assets/"
