version = 1

[exclude]
# Exclude all test and spec files
paths = [
  "**/*_test.rb",
  "**/*_spec.rb",
  "**/spec/**",
  "**/test/**",
  "**/features/**",
  "**/fixtures/**",
  "**/dummy/**",
  "**/test/**/*",
  "**/spec/**/*",
  ".rspec",
  ".simplecov",
  "spec_helper.rb",
  "rails_helper.rb"
]

# Ignore code coverage for test files
coverage = { exclude_patterns = ["**/*_spec.rb", "**/spec/**/*", "**/test/**/*"] }

[[analyzers]]
name = "javascript"

disabled = false

[analyzers.meta]
environment = [
  "browser"
]

[[analyzers]]
name = "ruby"

disabled = false

[analyzers.meta]
  [analyzers.meta.rails]
  enabled = true
  version = "6.1"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"
