name: CI

on:
  push:
    branches: [ main, master, ipay-feature-update1 ]
  pull_request:
    branches: [ main, master, ipay-feature-update1 ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.8
        bundler-cache: true
    
    - name: Install SQLite and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev
        
    - name: Setup test environment
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        
    - name: Run tests
      env:
        RAILS_ENV: test
        BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
      working-directory: ${{ github.workspace }}
      run: |
        # Make the test script executable and run it
        chmod +x run_tests.sh
        ./run_tests.sh
