name: Run RSpec Tests

on:
  push:
    branches: [ main, master, ipay-feature-update1 ]
  pull_request:
    branches: [ main, master, ipay-feature-update1 ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: spree_ipay_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/spree_ipay_test
      TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/spree_ipay_test
      DISABLE_SPRING: 1
      RAILS_MASTER_KEY: 1234567890abcdef1234567890abcdef  # Add a dummy key for test environment
      SECRET_KEY_BASE: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true
        bundler: 2.4.22  # Specific bundler version that works well with Spree 4.5

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle config set without 'development'
        bundle install --jobs 4 --retry 3

    - name: Set up test database
      run: |
        # Generate test app if it doesn't exist
        if [ ! -d "spec/dummy" ]; then
          bundle exec rails new spec/dummy --skip-git --database=postgresql --skip-test --skip-system-test --skip-turbolinks --skip-webpack-install
          
          # Add Spree to the test app
          cd spec/dummy
          echo "gem 'spree', '~> 4.5.0'" >> Gemfile
          echo "gem 'spree_gateway', '~> 3.11.1'" >> Gemfile
          echo "gem 'spree_auth_devise', '~> 4.5.0'" >> Gemfile
          bundle install
          
          # Run Spree install
          bundle exec rails g spree:install --auto-accept --user_class=Spree::User
          bundle exec rails g spree:auth:install
          bundle exec rails g spree_gateway:install
          
          # Set up database
          bundle exec rails db:create
          bundle exec rails db:migrate
          cd ../..
        fi

    - name: Run tests
      run: bundle exec rspec
