name: Run RSpec Tests

on:
  push:
    branches: [ main, master, ipay-feature-update1 ]
  pull_request:
    branches: [ main, master, ipay-feature-update1 ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DISABLE_SPRING: 1
      RAILS_MASTER_KEY: 1234567890abcdef1234567890abcdef
      SECRET_KEY_BASE: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true
        bundler: 2.4.22

    - name: Set up test database
      run: |
        # Create test app directory
        mkdir -p spec/dummy
        cd spec/dummy
        
        # Create a basic Rails app with SQLite
        bundle _2.4.22_ exec rails new . --force \
          --skip-bootsnap \
          --skip-jbuilder \
          --skip-test \
          --skip-system-test \
          --skip-turbolinks \
          --skip-webpack-install \
          --skip-sprockets \
          --database=sqlite3
        
        # Create a new Gemfile with required gems
        cat > Gemfile << 'EOL'
source 'https://rubygems.org'

gem 'rails', '~> 7.1.4'
gem 'sqlite3', '~> 2.0'

# Spree
gem 'spree', '~> 4.6.0'
gem 'spree_gateway', '~> 3.10.0'
gem 'spree_auth_devise', '~> 4.6.0'
gem 'spree_extension', '~> 0.1.0'
gem 'spree_ipay', path: '../..'

# Ransack with Rails 7.1 compatibility
gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'main'
gem 'polyamorous', '~> 2.0', require: false

# Testing
group :development, :test do
  gem 'rspec-rails', '~> 6.1.0'
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'database_cleaner', '~> 2.0'
  gem 'shoulda-matchers', '~> 5.0'
end

# Web server
gem 'puma', '~> 6.0'
EOL

        # Install gems with specific bundler version
        gem install bundler -v 2.4.22
        bundle _2.4.22_ config set --local deployment 'true'
        bundle _2.4.22_ install --jobs 4 --retry 3 --verbose
        
        # Install RSpec
        bundle _2.4.22_ exec rails generate rspec:install
        
        # Run Spree install
        bundle _2.4.22_ exec rails g spree:install --auto-accept --user_class=Spree::User
        bundle _2.4.22_ exec rails g spree:auth:install
        bundle _2.4.22_ exec rails g spree_gateway:install
        
        # Set up database
        bundle _2.4.22_ exec rails db:create
        bundle _2.4.22_ exec rails db:migrate
        
        # Generate RSpec binstub
        bundle _2.4.22_ binstubs rspec-core

    - name: Run tests
      run: |
        cd spec/dummy
        # Use the binstub to run RSpec
        bin/rspec ../../spec
