name: Run RSpec Tests

on:
  push:
    branches: [ main, master, ipay-feature-update1 ]
  pull_request:
    branches: [ main, master, ipay-feature-update1 ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: spree_ipay_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/spree_ipay_test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle config set without 'development'
        bundle install --jobs 4 --retry 3

    - name: Set up test database
      run: |
        # Create the test app
        bundle exec rake test_app
        
        # Set up database
        cd spec/dummy
        RAILS_ENV=test bundle exec rails db:create db:migrate
        cd ../..

    - name: Run tests
      run: bundle exec rspec
